lista_de_tarefas/tarefas/urls.py
from django.urls import path

from lista_de_tarefas.tarefas.views import TasksListView, TasksEditView, TasksCreateView, TasksDeleteView
app_name = "tarefas"

urlpatterns = [
    path('', TasksListView.as_view(), name='url_index'),
    path('edit/<int:pk>', TasksEditView.as_view(), name='url_edita'),
    path('insert', TasksCreateView.as_view(), name='url_insere'),
    path('delete/<int:pk>', TasksDeleteView.as_view(), name='url_deleta'),
]

lista_de_tarefas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("lista_de_tarefas.tarefas.urls")),
    path('admin/', admin.site.urls),
]

lista_de_tarefas/tarefas/models.py
from django.db import models

# Create your models here.
# model que representa uma tarefa
class Tarefa(models.Model):
    nome = models.CharField(max_length=100)
    data = models.DateField()
    hora = models.TimeField()
    data_criacao = models.DateTimeField(auto_now_add=True)
    descricao = models.TextField(null=True,blank=True)

    class Meta:
        verbose_name_plural = 'Tarefas'
    
    def __str__(self):
        return self.nome

lista_de_tarefas/tarefas/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from .models import Tarefa
from .form import TarefaForm
from django.urls import reverse_lazy

class TasksListView(ListView):
    model = Tarefa
    template_name = 'tarefas/index.html'
    context_object_name = 'tarefas'

class TasksEditView(UpdateView):
    model = Tarefa
    template_name = 'tarefas/insere.html'
    form_class = TarefaForm
    success_url = '/'
    def get_context_data(self, **kwargs):
        context = super(TasksEditView, self).get_context_data(**kwargs)
        context['tipo'] = 2
        return  context

class TasksCreateView(CreateView):
    model = Tarefa
    template_name = 'tarefas/insere.html'
    form_class = TarefaForm
    success_url = '/'
    def get_context_data(self, **kwargs):
        context = super(TasksCreateView, self).get_context_data(**kwargs)
        context['tipo'] = 1
        return context

class TasksDeleteView(DeleteView):
    model = Tarefa
    success_url = '/'

# #Inserir uma nova tarefa na lista
# def insere_tarefa(request):
#     form = TarefaForm(request.POST or None)
#     dados = {}
#     dados['form'] = form
#     dados['tipo'] = 1
#     if form.is_valid():
#         form.save()
#         return redirect('tarefas:url_index')
#     return render(request, 'tarefas/insere.html', dados)
#
# #Atualiza uma tarefa de acordo com o id informado
# def edita_tarefa(request, pk):
#     tarefa = Tarefa.objects.get(pk=pk)
#     form = TarefaForm(request.POST or None, instance=tarefa)
#     dados = {}
#     dados['form'] = form
#     dados['tipo'] = 2
#     if form.is_valid():
#         form.save()
#         return redirect('tarefas:url_index')
#     return render(request, 'tarefas/insere.html', dados)
#
# #Deleta uma tarefa de acordo com o id informado
# def deleta_tarefa(request,pk):
#     tarefa = Tarefa.objects.get(pk=pk)
#     tarefa.delete()
#     return redirect('tarefas:url_index')

lista_de_tarefas/tarefas/templates/tarefas/index.html
<!--Página que apresenta a lista de tarefas com opções de editar e excluir uma tarefa
Também existe um botão que redireciona para a página de inserção de uma nova tarefa-->
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Tarefas</title>

    <!--CSS bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
    <!--Scripts bootstrap-->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>


    <div class="container">
        <!--Título da página-->
        <blockquote class="blockquote text-center">
            <h1>Lista de Tarefas</h1>
        </blockquote>

        <!--Tabela contendo as tarefas-->
        {% if not tarefas %}
        <blockquote class="blockquote text-center">
            <br />
            <h3>A lista de tarefas está vazia</h3>
        </blockquote>
        {% else %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Data</td>
                    <th>Nome</td>
                    <th>Hora</td>
                    <th>Descrição</td>
                    <th>
                        </td>
                    <th>
                        </td>
                </tr>
            </thead>
            {% for tarefa in tarefas %}
            <tr>
                <td>{{ tarefa.data }}</td>
                <td>{{ tarefa.nome }}</td>
                <td>{{ tarefa.hora }}</td>
                <td>{{ tarefa.descricao }}</td>
                <td><a href="{% url 'tarefas:url_edita' tarefa.id %}" class="badge badge-warning">Editar</a></td>
                <td><a href="{% url 'tarefas:url_deleta' tarefa.id %}" class="badge badge-danger">Excluir</a>
                </td>
            </tr>

            {% endfor %}
        </table>
        {% endif %}
        <!--Botão para página de inserção de uma nova tarefa-->
        <blockquote class="blockquote text-center">
            <a class="btn btn-primary" href="{% url 'tarefas:url_insere' %}" role="button">Inserir Tarefa</a>
        </blockquote>
    </div>
</body>

</html>

lista_de_tarefas/tarefas/templates/tarefas/insere.html
<!--Página contendo o formulário para inserção e edição de uma tarefa-->
{% load static %}
{% load bootstrap %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Tarefas</title>

    <!--CSS bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
    <!--Scripts bootstrap-->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

    <!--Título da página-->
    <div class="container .mr-md-3">
        {% if tipo == 1 %}
        <blockquote class="blockquote text-center">
            <h1>Inserir Tarefas</h1>
        </blockquote>
        {% elif tipo == 2 %}
        <blockquote class="blockquote text-center">
            <h1>Editar Tarefas</h1>
        </blockquote>
        {% endif %}
    </div>

    <!--Formulário de dados-->
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            {{ form|bootstrap }}
            <button type="submit" class="btn btn-success">Salvar</button>
            <button type="reset" class="btn btn-primary">Limpar</button>
            <a class="btn btn-secondary" href="{% url 'tarefas:url_index' %}" role="button">Voltar</a>
        </form>
    </div>
</body>

</html>

lista_de_tarefas/tarefas/templates/tarefas/tarefa_confirm_delete.html
<!--Página contendo o formulário para inserção e edição de uma tarefa-->
{% load static %}
{% load bootstrap %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Tarefas</title>

    <!--CSS bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
    <!--Scripts bootstrap-->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <span class="border border-primary">
    <div class="container">

            <form method="post">{% csrf_token %}
                <p>Deseja Excluir a tarefa "{{ tarefa.nome }}"?</p>
                <input type="submit" value="Confirmar" class="btn btn-danger">
                <a href="{% url 'tarefas:url_index' %}" class="btn btn-primary">Voltar</a>
            </form>

    </div>
    </span>


</body>

</html>